// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace BlazorComAPI.Server.Migrations
{
    [DbContext(typeof(DbContextServer))]
    [Migration("20250409003004_FeaturedProducts")]
    partial class FeaturedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProdutoVariante_TBL");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 1,
                            Name = "Teclado Padrão",
                            OriginalPrice = 149.99m,
                            Price = 99.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 3,
                            Name = "Teclado Médio",
                            OriginalPrice = 159.99m,
                            Price = 109.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 2,
                            Name = "Rato Pequeno",
                            OriginalPrice = 89.99m,
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 4,
                            Name = "Rato Grande",
                            OriginalPrice = 99.99m,
                            Price = 69.99m
                        });
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("featured")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Description = "Teclado com switches azuis",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Teclado Mecânico",
                            featured = true
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Description = "Mouse com DPI ajustável e LED RGB",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Rato Gamer",
                            featured = false
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Description = "Um guia de boas práticas de programação por Robert C. Martin.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Livro: Clean Code",
                            featured = false
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Description = "Aborda modelagem de software baseada em domínio.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Livro: Domain-Driven Design",
                            featured = false
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Description = "Um thriller de ficção científica dirigido por Christopher Nolan.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Filme: Inception",
                            featured = true
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Description = "Exploração espacial para salvar a humanidade.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Filme: Interstellar",
                            featured = true
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            Description = "RPG de mundo aberto com narrativa envolvente.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "Jogo: The Witcher 3",
                            featured = true
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Description = "Kratos em sua jornada épica no mundo nórdico.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Title = "God of War",
                            featured = true
                        });
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("Shared.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProductType_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Padrão"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tamanho Pequeno"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tamanho Médio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tamanho Grande"
                        });
                });

            modelBuilder.Entity("ProductVariant", b =>
                {
                    b.HasOne("Produto", "produto_nav")
                        .WithMany("productVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.ProductType", "productType")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productType");

                    b.Navigation("produto_nav");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.HasOne("Shared.Categoria", "categoria")
                        .WithMany("produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Navigation("productVariants");
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Navigation("produtos");
                });

            modelBuilder.Entity("Shared.ProductType", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
