// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace BlazorComAPI.Server.Migrations
{
    [DbContext(typeof(DbContextServer))]
    [Migration("20250407232550_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorComAPI.Shared.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Description = "Teclado com switches azuis",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 59.99m,
                            Title = "Teclado Mecânico"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Description = "Mouse com DPI ajustável e LED RGB",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 29.99m,
                            Title = "Rato Gamer"
                        });
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 0,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 0,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 0,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorComAPI.Shared.Produto", b =>
                {
                    b.HasOne("Shared.Categoria", "categoria")
                        .WithMany("produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Navigation("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
