// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace BlazorComAPI.Server.Migrations
{
    [DbContext(typeof(DbContextServer))]
    partial class DbContextServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorComAPI.Shared.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Description = "Teclado com switches azuis",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 59.99m,
                            Title = "Teclado Mecânico"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Description = "Mouse com DPI ajustável e LED RGB",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 29.99m,
                            Title = "Rato Gamer"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Description = "Um guia de boas práticas de programação por Robert C. Martin.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 45.90m,
                            Title = "Livro: Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Description = "Aborda modelagem de software baseada em domínio.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 68.00m,
                            Title = "Livro: Domain-Driven Design"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Description = "Um thriller de ficção científica dirigido por Christopher Nolan.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 19.99m,
                            Title = "Filme: Inception"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Description = "Exploração espacial para salvar a humanidade.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 24.99m,
                            Title = "Filme: Interstellar"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            Description = "RPG de mundo aberto com narrativa envolvente.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 39.90m,
                            Title = "Jogo: The Witcher 3"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Description = "Kratos em sua jornada épica no mundo nórdico.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Price = 49.99m,
                            Title = "Jogo: God of War"
                        });
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias_TBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 0,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 0,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 0,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorComAPI.Shared.Produto", b =>
                {
                    b.HasOne("Shared.Categoria", "categoria")
                        .WithMany("produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("Shared.Categoria", b =>
                {
                    b.Navigation("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
